branches:
  only:
    - master
    - develop

language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
install: "python setup.py -q install"
script: py.test -q --tb short

#Database
addons:
  postgresql: "9.3"

before_script:
  - sh -c "if [ '$DATABASE_URL' = 'postgresql+psycopg2://postgres@127.0.0.1/dataset'  ]; then psql -c 'DROP DATABASE IF EXISTS scrom_test;' -U postgres; fi"
  - sh -c "if [ '$DATABASE_URL' = 'postgresql+psycopg2://postgres@127.0.0.1/dataset'  ]; then psql -c 'create database scrom_test;' -U postgres; fi"

