branches:
  only:
    - master
    - develop

language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
install: "python setup.py -q install"
script: py.test

#Database
addons:
  postgresql: "9.3"

before_script:
  - psql -c 'DROP DATABASE IF EXISTS scrom_test;' -U postgres
  - psql -c 'create database scrom_test;' -U postgres

